---
name: 01 Basic Docker Build
# Basic GH Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-actions@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-actions@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: nginx:1.17.3
